apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitlab-argocd
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: http://192.168.56.110:8585/root/wills_app.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab
  