Vagrant.configure("2") do |config|
   config.vm.synced_folder ".", "/IOT"
   config.vm.box = "generic/alpine317"
   config.vm.hostname = "aleconteS"
   config.vm.network :private_network, ip: "192.168.56.11"
   config.vm.provision :shell, path: "bootstrap.sh"
   config.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", 1024]
      vb.customize ["modifyvm", :id, "--cpus", 1]
      vb.name = machine = "new"
      end
   end

