Vagrant.configure("2") do |config|
   config.vm.synced_folder ".", "/IOT"
   servers=[
      {
         :hostname => "ldes-couS",
         :ip => "192.168.56.110",
      },
      {
         :hostname => "ldes-couSW",
         :ip => "192.168.56.111",
      }
   ]

   # Boucle pour creer chaque machine a partir  des variable du tableau servers
   servers.each do |machine|
      config.vm.define machine[:hostname] do |node|
         node.vm.box = "generic/alpine317"
         node.vm.hostname = machine[:hostname]
         node.vm.network :private_network, ip: machine[:ip]
         node.vm.provision :shell, path: "scripts/bootstrap.sh"
         node.vm.provider "virtualbox" do |vb|
            vb.customize ["modifyvm", :id, "--memory", 1024]
            vb.customize ["modifyvm", :id, "--cpus", 1]
            vb.name = machine[:hostname]
            #vb.gui = true
         end
      end
   end
end

