
Vagrant.configure("2") do |config|
   config.vm.synced_folder ".", "/IOT"
   config.vm.box = "generic/alpine317"
   config.vm.hostname = "P3"
   config.vm.network :private_network, ip: "192.168.56.110"
   config.vm.provision :shell, path: "install.sh"
   config.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", 4096]
      vb.customize ["modifyvm", :id, "--cpus", 4]
      vb.name = machine = "argocdMachine"
      end
   end

